const contohriwayatpendidikanmahasiswa = {
  state: {
    contohriwayatpendidikanmahasiswa: {
      header: [
        'nama_mahasiswa',
        'jenis_kelamin',
        'jalan',
        'rt',
        'rw',
        'kelurahan',
        'kode_pos',
        'nisn',
        'nik',
        'tempat_lahir',
        'tanggal_lahir',
        'nama_ayah',
        'tanggal_lahir_ayah',
        'id_pendidikan_ayah',
        'id_pekerjaan_ayah',
        'id_penghasilan_ayah',
        'id_kebutuhan_khusus_ayah',
        'nama_ibu_kandung',
        'tanggal_lahir_ibu',
        'id_pendidikan_ibu',
        'id_pekerjaan_ibu',
        'id_penghasilan_ibu',
        'id_kebutuhan_khusus_ibu',
        'nama_wali',
        'tanggal_lahir_wali',
        'id_pendidikan_wali',
        'id_pekerjaan_wali',
        'id_penghasilan_wali',
        'id_kebutuhan_khusus_mahasiswa',
        'telepon',
        'handphone',
        'email',
        'penerima_kps',
        'id_wilayah',
        'id_agama',
        'kewarganegaraan',
        'nim',
        'id_jenis_daftar',
        'id_jalur_daftar',
        'id_periode_masuk',
        'tanggal_daftar',
        'kode_perguruan_tinggi',
        'nama_perguruan_tinggi',
        'kode_program_studi',
        'nama_program_studi',
        'nama_jenjang_pendidikan',
        'sks_diakui',
        'nama_perguruan_tinggi_asal',
        'nama_program_studi_asal',
        'nama_jenjang_pendidikan_asal',
        'id_pembiayaan'
      ],
      data: [[
        'ADITYA PRATAMA',
        'L',
        'Jalan Pratista Selatan No. 29',
        '05',
        '21',
        'Antapani Kidul',
        40291,
        '0999999999',
        '3273202507989',
        'BANDUNG',
        '1998-11-30',
        'SATRIO ADIPUTRA',
        '1970-11-30',
        30,
        10,
        15,
        0,
        'MURNI IRAWATI',
        '1972-10-30',
        30,
        1,
        11,
        0,
        '',
        '',
        '',
        '',
        '',
        0,
        22227214054,
        100000000000,
        'a@gmail.com',
        0,
        160217,
        1,
        'ID',
        '11181000',
        1,
        1,
        '20182',
        '2018-07-25',
        '043115',
        'Sekolah Tinggi Farmasi Bandung',
        '48201',
        'Farmasi',
        'S1',
        '',
        '',
        '',
        '',
        ''
      ]]
    }
  }
}

export default contohriwayatpendidikanmahasiswa
